# Generated by Django 5.2.7 on 2025-11-02 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EspecificacionesTecnicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potencia_w', models.PositiveIntegerField(verbose_name='Potencia (W)')),
                ('rango_frecuencia_min', models.PositiveIntegerField(verbose_name='Rango frecuencia mínima (Hz)')),
                ('rango_frecuencia_max', models.PositiveIntegerField(verbose_name='Rango frecuencia máxima (Hz)')),
                ('material_cono', models.CharField(max_length=50)),
                ('material_tweeter', models.CharField(choices=[('Seda', 'Seda'), ('Aluminio', 'Aluminio'), ('Berilio', 'Berilio'), ('Titanio', 'Titanio'), ('Fibra de carbono', 'Fibra de carbono')], max_length=50)),
                ('cantidad_entradas', models.PositiveIntegerField()),
                ('peso_kg', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('precio_usd', models.PositiveIntegerField(verbose_name='Precio (USD)')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='instrumentos.categoria')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('especificaciones', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='instrumentos.especificacionestecnicas')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumentos.marca')),
            ],
        ),
    ]
