# Generated by Django 5.2.7 on 2025-11-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='monitores/', verbose_name='Imagen del Monitor'),
        ),
    ]
